### ISSUE TITLE
Keeping api keys in secrets.

### ISSUE THREAD

**Issue by benshalev849** [dtomlinson91/traefik-api-key-middleware#1]
Hello, first of all i wanted to thank you for making this plugin (Been needing this for a while haha).

I wanted to ask if there is a way to create the key list or just 1 key in a secret when using k8s for example.
Atm i saw it's in simple text which can compromise the application.
Ty very much for the contribution!

**Comment by dtomlinson91** [comment]
Hey @benshalev849 

The Middleware CRD is written by Traefik, unfortunately when writing a plugin you have no control over it.

Looking through I saw this [issue](https://github.com/traefik/traefik/issues/8994) on Traefik a while ago which looks like it was [merged](https://github.com/traefik/traefik/pull/9103) but I can't find reference to it in the docs. Looks like it's what you're after?

```
apiVersion: v1
kind: Secret
metadata:
  name: name
  namespace: default

data:
  key: dGhpc19pc190aGVfdmVyeV9kZWVwX3NlY3JldA==

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-secret
  namespace: default

spec:
  plugin:
    test-secret:
      secret_0:
        secret_1:
          secret_2:
            user: admin
            secret: urn:k8s:secret:name:key
```

Personally we use Helm with the [Helm Secrets](https://github.com/jkroepke/helm-secrets) plugin to store the API keys encrypted with SOPS in the chart when deploying the middleware but if that functionality is in there I'd swap to using that and I'll update the readme with an example as it's much better than plain text.
